### PR TITLE
 Use pip3 and python3

### PR DESCRIPTION
**Pull request by wesleyw72**
We use Python 3 so we should be using pip3 and python3 commands. It's not a guarantee that pip links through to pip3 on all systems so we should explicitly call the correct version. Specifically hitting this issue on Ubuntu 16.04 build agents.

### CODE REVIEW

**Comment by icantsayrural** [comment]
Do we also have to change line `commandLine 'pipenv', 'run', 'pip', '--version'` ?

**Comment by GeorgeNash** [comment]
And change the `python` commands to `python3`?

**Comment by wesleyw72** [comment]
Yeah both good comments, will do some testing to make sure that works (on my machine and double check on a build agent).

**Comment by migwellian** [comment]
The `pip` inside your `pipenv` can be different to the `pip` outside you `pipenv`.

I expect that inside your `pipenv` you don't need to specify `pip3`, but it would still be better to be explicit and use `pip3` throughout.

**Pull request merged**
