### PR TITLE
[Do not merge] An example of bad formatting failing

### PR DESCRIPTION
**Pull request by Pinpickle**
This PR includes changes that violate our formatting rules. It's an example of how tests will fail in this case.

### CODE REVIEW

**Comment by Pinpickle** [comment]
You heard it from Travis, it's failing:

image

**Comment by migwellian** [comment]
Does it tell you on the command line what the violations were?

**Comment by Pinpickle** [comment]
@migwellian yes. If you run `gradle check`, it will give you the same message as screenshot above

**Comment by migwellian** [comment]
Yes, but what I meant was: does it explain what's wrong, i.e. which rule has been violated.

I tried it out myself - the answer is no, but I guess that doesn't matter as the user doesn't really need to know/care about the details, they just need to run `spotlessApply` (which the error message instructs them to do).

And of course in the case of your custom rule, you get the custom error message.

**Pull request closed without merging**
